Feat/tasks event
GandalfClub/gandalf-app pull request #120
Opened 2021-03-11 16:55 UTC by MaxProtos

2021-03-15 11:59 UTC, maximwow70 commented on frontend/src/app/libs/code-editors/monaco-editor/monaco-editor.component.html
> +  <div class="editor-container" #editorContainer>
Why we need additional wrapper here?

2021-03-15 11:59 UTC, maximwow70 commented on frontend/src/app/libs/code-editors/monaco-editor/monaco-editor.component.ts
> +  public onBlur = () => {};
Type should be provided.

2021-03-15 11:59 UTC, maximwow70 commented on frontend/src/app/libs/common-components/components/select/select.component.ts
> +      arrayTime.push({
You can use spread operator here like:
```
arrayTime = [
   ...arrayTime,
   {...},
   {...}
]
```

2021-03-15 11:59 UTC, maximwow70 commented on frontend/src/app/libs/common-components/components/slide-toggle/slide-toggle.component.ts
> +  public labelPosition: 'before' | 'after';
Please, define new type for labelPosition.
Just `LabelPosition`.

2021-03-15 11:59 UTC, maximwow70 commented on frontend/src/app/libs/common-components/components/tab-navigation/tab-navigation.component.ts
> +    .pipe(
Looks like here something happened with formatting.

2021-03-15 11:59 UTC, maximwow70 commented on frontend/src/app/libs/common-components/components/tasks-creator/tasks-creator/tasks-creator.component.html
> +      <div *ngIf="!isTaskNameEditMode" class="tasks-creator__name-editor">
class always should be the first attribute of element to good readability.

2021-03-15 11:59 UTC, maximwow70 commented on frontend/src/app/libs/common-components/components/tasks-creator/tasks-creator/tasks-creator.component.ts
> +    .pipe(takeUntil(this.destroyedSource$))
The same with formatting.

2021-03-15 11:59 UTC, maximwow70 commented on frontend/src/app/libs/common-components/components/tasks-creator/tasks-creator/tasks-creator.component.ts
> +        this.taskTypeOptions.length = 0;
Looks like a hack.
Please, use map here and reassign taskTypeOptions.

2021-03-15 11:59 UTC, maximwow70 commented on frontend/src/app/libs/common-components/components/tasks-creator/tasks-creator/tasks-creator.component.ts
> +        if (this.selectedTaskType === TasksTypes.coding && this.isMentorCheckSelected === false) {
`this.isMentorCheckSelected === false` the same as `!this.isMentorCheckSelected`

2021-03-15 11:59 UTC, maximwow70 commented on frontend/src/app/libs/event-creation/event-creation.component.ts
> +  public getTaskCreationForm(task: ITask): void {
Function name started with get, then this function return something.
Looks like here need to name set..

2021-03-15 11:59 UTC, maximwow70 commented on frontend/src/app/libs/event-creation/store/event.actions.ts
> +	SetTitleForGeneralEvent = '[NewEvent] set title for new event',
Something happened with formatting.

2021-03-15 11:59 UTC, maximwow70 commented on frontend/src/app/libs/event-creation/store/event.facade.ts
> +	get generalTitle$(): Observable<string> {
public missing.

2021-03-15 11:59 UTC, maximwow70 commented on frontend/src/app/libs/event-creation/store/event.facade.ts
> +  }
Formatting.

2021-03-15 11:59 UTC, maximwow70 commented on frontend/src/app/libs/event-creation/store/event.reducer.ts
> +        general: {
Please, fix formatting.

2021-03-15 12:24 UTC, clain-atomi requested changes

2021-03-15 12:24 UTC, clain-atomi commented on frontend/src/app/libs/common-components/components/button/button.component.ts
> +  public iconButton: boolean = false;
not sure about this input, we have icon-button to work with icons

2021-03-15 12:24 UTC, clain-atomi commented on frontend/src/app/libs/common-components/components/icon/icon.component.html
> +  [ngStyle]="{ 'color' : color }">
[style.color]="color"

2021-03-15 12:24 UTC, clain-atomi commented on frontend/src/app/libs/common-components/components/input/input.component.html
> +  [ngClass]="{ 'no-paddings' : noPaddings }"
same here

2021-03-15 12:24 UTC, clain-atomi commented on frontend/src/app/libs/common-components/components/input/input.component.html
>  	[style.width] = "widthInput"
unnecessary space near =

2021-03-15 12:24 UTC, clain-atomi commented on frontend/src/app/libs/common-components/components/select/models/select-option.ts
> +export interface ISelectOption {
just `SelectOption`

2021-03-15 12:24 UTC, clain-atomi commented on frontend/src/app/libs/common-components/components/slide-toggle/slide-toggle.component.ts
> +  public labelPosition: 'before' | 'after';
create enum

2021-03-15 12:24 UTC, clain-atomi commented on frontend/src/app/libs/common-components/components/tab-navigation/models/tabs.ts
> +  'generalTab',
set string values to better readability in templates, `Tabs { General: 'general' ... }`

2021-03-15 12:24 UTC, clain-atomi commented on frontend/src/app/libs/common-components/components/tab-navigation/tab-navigation.component.html
> +	 (click)="changePage(tabsEnum.generalTab)">GENERAL</div>
changePage('general')
or create 3 methods like `switchToGeneral()` and etc

2021-03-15 12:24 UTC, clain-atomi commented on frontend/src/app/libs/common-components/components/tab-navigation/tab-navigation.component.ts
>  	public get invitationsTab(): boolean {
`isInvitationsLabActive` or something like that

2021-03-15 12:24 UTC, clain-atomi commented on frontend/src/app/libs/common-components/components/tasks-creator/models/task.ts
> +export interface IAnswer {
No need to use I for iterfaces, it's likely more .net practice :)

2021-03-15 12:24 UTC, clain-atomi commented on frontend/src/app/libs/common-components/components/tasks-creator/models/tasks-creator.ts
> +export enum TasksTypes {
Coding  = 'CODING'

2021-03-15 12:24 UTC, clain-atomi commented on frontend/src/app/libs/common-components/components/tasks-creator/tasks-creator/tasks-creator.component.html
> +            [labelPosition]="'before'"
avoid cases like thin across application [...]="'...'" can be transformed to ...="..."

2021-03-15 12:24 UTC, clain-atomi commented on frontend/src/app/libs/common-components/components/tasks-creator/tasks-creator/tasks-creator.component.html
> +                <mat-radio-button class="mat-form-field-wrapper" value="{{ i.toString() }}"></mat-radio-button>
no need .toString here

2021-07-21 13:58 UTC, clain-atomi requested changes

2021-07-22 13:01 UTC, merged