Feat/event popover
GandalfClub/gandalf-app pull request #41
Opened 2020-09-07 10:26 UTC by Keczale

besides my component i added material theme deeppurple-amber to style.scss

2020-09-07 11:18 UTC, maximwow70 commented on frontend/src/app/libs/common-components/event-poover/event-poover.component.spec.ts
> +		declarations: [ EventPooverComponent ],
The same with spaces.

2020-09-07 11:18 UTC, maximwow70 commented on frontend/src/app/libs/common-components/event-poover/event-poover.component.spec.ts
> +		let title: AbstractControl = component.eventPopoverForm.controls['title']
missing ;

2020-09-07 11:18 UTC, maximwow70 commented on frontend/src/app/libs/common-components/event-poover/event-poover.component.spec.ts
> +	//   titleEl.nativeElement.value = testValue;      don't get this data??
The same with commented code.

2020-09-07 11:18 UTC, maximwow70 commented on frontend/src/app/libs/common-components/event-poover/event-poover.component.spec.ts
> +		let errors = title.errors || {};
Please, use const instead of let if you don't reassign variable.

2020-09-07 11:40 UTC, maximwow70 commented on frontend/src/app/libs/common-components/event-poover/event-poover.component.html
> +    <div  mat-dialog-action class="event-popover__btn-wrap">
Also here before mat-dialog 2 spaces, should be one.

2020-09-07 14:14 UTC, clain-atomi requested changes

2020-09-07 14:14 UTC, clain-atomi commented on frontend/src/app/app.component.ts
> +import { EventPooverComponent } from './libs/common-components/event-poover/event-poover.component';
typo here => `EventPopoverComponent`, same for path

2020-09-07 14:14 UTC, clain-atomi commented on frontend/src/app/libs/common-components/event-poover/event-poover.component.html
> +</div>
please end empty new line at the end of file

2020-09-07 14:14 UTC, clain-atomi commented on frontend/src/app/libs/common-components/event-poover/event-poover.component.scss
> +    &__btn-wrap{
add space before `{`

2020-09-07 14:14 UTC, clain-atomi commented on frontend/src/app/libs/common-components/event-poover/event-poover.component.ts
> +import { Component, OnInit } from '@angular/core';
let's fire some @Output with updated Partial<Event> when user creates new event

2020-09-07 14:14 UTC, clain-atomi commented on frontend/src/app/libs/common-components/event-poover/event-poover.component.ts
> +import { Component, OnInit } from '@angular/core';
also create public methods `.open()` and `.close` to open or close this popover.
best use case for this component is something like
`<create-draft-event-popover #draftEventPopover (creating)="createDraftEvent($event)"></create-draft-event-popover>
<button (click)="draftEventPopover.open()">Some Button</button>`

2020-09-07 14:14 UTC, clain-atomi commented on frontend/src/app/libs/common-components/event-poover/event-poover.component.ts
> +import { Component, OnInit } from '@angular/core';
Please rename component to `create-draft-event-popover`

2020-09-07 14:14 UTC, clain-atomi commented on frontend/src/app/app.component.ts
> +	constructor(public dialog: MatDialog) { }
please remove code from app component

2020-09-07 14:15 UTC, clain-atomi commented
Also please merge latest master into your branch

2020-09-08 17:10 UTC, Keczale commented
Блок установки:
<app-create-draft-event-popover 
  #draftEventPopover
  hidden
  (creating)="createDraftEvent($event)">
</app-create-draft-event-popover>

2020-09-09 07:06 UTC, clain-atomi requested changes

2020-09-09 07:06 UTC, clain-atomi commented on frontend/src/app/libs/common-components/create-draft-event-popover/create-draft-event-popover.component.html
> +            [class.disabed]="eventPopoverForm.controls['title'].invalid">
typo `.disabled`

2020-09-09 07:06 UTC, clain-atomi commented on frontend/src/app/libs/common-components/create-draft-event-popover/create-draft-event-popover.component.html
> +            (click)=submitEventPopover()
add `"`

2020-09-09 07:06 UTC, clain-atomi commented on frontend/src/app/libs/common-components/create-draft-event-popover/create-draft-event-popover.component.html
> +            [class.disabed]="eventPopoverForm.controls['title'].invalid">
also you adding this class, but a not seeing it in scss file, do we really need it?

2020-09-09 07:06 UTC, clain-atomi commented on frontend/src/app/libs/common-components/create-draft-event-popover/create-draft-event-popover.component.ts
> +	public openDialog(): void {
lets simplify name `open`

2020-09-09 08:52 UTC, clain-atomi approved these changes

2020-09-09 08:52 UTC, merged