feat: checkbox common component
GandalfClub/gandalf-app pull request #75
Opened 2020-10-02 12:10 UTC by Tanyashinke

2020-10-06 08:42 UTC, clain-atomi requested changes

2020-10-06 08:42 UTC, clain-atomi commented on frontend/src/app/libs/common-components-demo/components/checkbox-demo/checkbox-demo.component.html
> +
add new line at the end of file

2020-10-06 08:42 UTC, clain-atomi commented on frontend/src/app/libs/common-components-demo/components/checkbox-demo/checkbox-demo.component.scss
> +}
add new line at the end of file

2020-10-06 08:42 UTC, clain-atomi commented on frontend/src/app/libs/common-components/components/checkbox/checkbox.theme.scss
> +}
add new line at the end of file

2020-10-06 08:42 UTC, clain-atomi commented on frontend/src/app/libs/common-components/components/checkbox/checkbox.component.html
> +</div>
add new line at the end of file

2020-10-06 08:42 UTC, clain-atomi commented on frontend/src/app/libs/common-components/components/checkbox/checkbox.component.html
> +		[value]="isDefined(valueField) ? option[valueField] : (index + 1)"
move to getter please

2020-10-14 09:18 UTC, Tanyashinke commented on frontend/src/app/libs/common-components/components/checkbox/checkbox.component.html
> +		[value]="isDefined(valueField) ? option[valueField] : (index + 1)"
I have moved this to the getValue

2020-10-14 10:08 UTC, clain-atomi approved these changes

2020-10-14 10:08 UTC, merged